# https://docs.rubocop.org/rubycop/

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'vender/**/*'

# Layout

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/ExtraSpacing:
  Exclude:
    - 'db/migrate/*.rb'

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Metrics double
Metrics/AbcSize:
  Max: 34 # 17

Metrics/BlockLength:
  Max: 50 # 25

Metrics/BlockNesting:
  Max: 6 # 3

Metrics/ClassLength:
  Max: 200 # 100
  Exclude:
    - 'test/**/*.rb'

Metrics/CyclomaticComplexity:
  Max: 14 # 7

Metrics/MethodLength:
  Max: 20 # 10
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - 'db/migrate/*.rb'

Metrics/ModuleLength:
  Max: 200 # 100

Metrics/ParameterLists:
  Max: 10 # 5
  MaxOptionalParameters: 6 # 3

Metrics/PerceivedComplexity:
  Max: 16 # 8

# Styles

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
  AllowModifiersOnSymbols: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatString:
  EnforcedStyle: percent

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/OneLineConditional:
  AlwaysCorrectToMultiline: true

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  MinSize: 8

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  MinSize: 8

# Bundler
# https://docs.rubocop.org/rubocop/cops_bundler.html

Bundler/OrderedGems:
  Enabled: false

# Rails
# https://docs.rubocop.org/rubocop-rails/cops_rails.html

Rails:
  Enabled: true

Rails/BulkChangeTable:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments
