# https://docs.rubocop.org/rubycop/

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'vender/**/*'

# Layout
Layout/ExtraSpacing:
  Exclude:
    - 'db/migrate/*.rb'

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 120

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Loose Metrics
Metrics/AbcSize:
  Max: 23

Metrics/BlockLength:
  Max: 38

Metrics/BlockNesting:
  Max: 5

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Max: 150

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 11

# Styles
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/WordArray:
  MinSize: 8

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/SymbolArray:
  MinSize: 8

# Bundler
Bundler/OrderedGems:
  Enabled: false

# Rails
Rails:
  Enabled: true

