# https://docs.rubocop.org/rubycop/

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'vender/**/*'

# Layout
Layout/ExtraSpacing:
  Exclude:
    - 'db/migrate/*.rb'

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 120

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Metrics double
Metrics/AbcSize:
  Max: 34 # 17

Metrics/BlockLength:
  Max: 50 # 25

Metrics/BlockNesting:
  Max: 6 # 3

Metrics/ClassLength:
  Max: 200 # 100

Metrics/CyclomaticComplexity:
  Max: 14 # 7

Metrics/MethodLength:
  Max: 20 # 10
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - 'db/migrate/*.rb'

Metrics/ModuleLength:
  Max: 200 # 100

Metrics/ParameterLists:
  Max: 10 # 5
  MaxOptionalParameters: 6 # 3

Metrics/PerceivedComplexity:
  Max: 16 # 8

# Styles

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
  AllowModifiersOnSymbols: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/WordArray:
  MinSize: 8

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/SymbolArray:
  MinSize: 8

# Bundler
Bundler/OrderedGems:
  Enabled: false

# Rails
Rails:
  Enabled: true

