require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Layout/ExtraSpacing:
  Exclude:
    - 'db/migrate/*.rb'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 120

Style/NumericLiterals:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# Loose Metrics
Metrics/AbcSize:
  Max: 23

Metrics/BlockLength:
  Max: 38

Metrics/BlockNesting:
  Max: 5

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Max: 150

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 11

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/WordArray:
  MinSize: 3
