require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Layout/ExtraSpacing:
  Exclude:
    - 'db/migrate/*.rb'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/NumericLiterals:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/LineLength:
  Max: 120

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
