# credentials のサンプル

secret_key_base: {{ランダム生成}}

database:
  username: ikamail
  password: pass

ldap:
  username: cn=bind,dc=example,dc=jp
  password: pass

mail:
  options:
    from: no-reply@example.jp
  url_options:
    protocol: https
    host: ikamail.example.jp
