## LDAP
# For development and test
ldap:
  host: localhost
  port: 389
  encryption: null
  base: dc=example,dc=jp
  auth: :sipmle
  username: cn=admin,dc=example,dc=jp
  password: pass
  user:
    dn: uid
    base: ou=Users
    class: posixAccount
  group:
    dn: cn
    base: ou=Groups
    class: posixGroup
  restrict:
    auth:
      groups:
        - admin
        - staff
